[package]
name = "jaq-formats"
version = "0.1.0"
edition = "2021"

[features]
default = ["std", "xml"]
std = []
xml = ["xmlparser"]

[dependencies]
jaq-json = { version = "1.1.0", path = "../jaq-json" }

xmlparser = { version = "0.13.6", optional = true }
