name: Build and check

on:
  push:
    branches: [ main ]
    paths:
      - '**.rs'
      - '**/Cargo.*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose

    - name: Check jaq-core without default features
      working-directory: jaq-core
      run: cargo check --no-default-features

    - name: Check jaq-std without default features
      working-directory: jaq-std
      run: cargo check --no-default-features

    - name: Check jaq-json without default features
      working-directory: jaq-json
      run: cargo check --no-default-features

    - name: Clippy
      run: cargo clippy -- -Dwarnings
