name: Build with MSRV (minimal supported Rust version)

on:
  workflow_dispatch:
  push:
    paths:
      - 'Cargo.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: dtolnay/rust-toolchain@1.63
    - name: Check jaq-json
      working-directory: jaq-json
      run: cargo check

    - uses: dtolnay/rust-toolchain@1.65
    - name: Check jaq
      working-directory: jaq
      run: cargo check
    - name: Build
      run: cargo build --verbose
