name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: dtolnay/rust-toolchain@1.65
    - name: Build
      run: cargo build --verbose
    - name: Check (without default features)
      working-directory: jaq-core
      run: cargo check --no-default-features
    - name: Lint
      run: cargo clippy -- -Dwarnings
    - name: Run tests
      run: cargo test --verbose
